# Generated by Django 5.0.2 on 2024-02-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=20, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('emailid', models.EmailField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('joining', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('AssignManager', models.CharField(blank=True, max_length=100)),
                ('AssignProject', models.CharField(blank=True, max_length=100)),
                ('profilepath', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
